server:
  port: 8189
  servlet:
    context-path: /sec
spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    enabled: true
