server:
  port: 8089
spring:
  application:
    name: rest-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:products_bd;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8289/eureka}