server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class: org.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products_bd?serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


